spring:
  datasource:
    druid:
      url: "jdbc:mysql://localhost:3306/spring_web?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false"
      username: "root"
      password: "root"
      max-active: 20