server:
  port: 8080
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  profiles:
    active: "dev,common-db"
  jackson:
    date-format: "yyyy-MM-dd hh:mm:ss"
# 配置mybatis
mybatis:
  # 扫描注册mapper.xml文件
  mapper-locations: "classpath:mapper/**/*.xml"
  # 设置别名
  type-aliases-package: "com.qf.cabinet.entity"
  # 设置mybatis核心配置文件
  configuration:
    map-underscore-to-camel-case: true
