spring:
  # 指定当前应用程序要使用的环境
  profiles:
    active: "dev,common-db"

  jackson:
    date-format: "yyyy-MM-dd hh:mm:ss"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_
      # 假删除字段的名称
      logic-delete-field: member_status
      logic-delete-value: 1
      logic-not-delete-value: 0

