
logging:
  level:
    com.qf: debug




spring:
  datasource:
    druid:
      url: "jdbc:mysql:///example01?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false"
      password: "1234"
      username: "root"
      max-active: 20
aliyun:
  oss:
    endpoint: "https://oss-cn-guangzhou.aliyuncs.com"
    access-key-id: "LTAI5tLp2votpCBiGkP8n2wp"
    secret-access-key: "YxQVvM99VTIag3dweI7f8wOIG4M4wc"
    bucket-name: "gz-qf-2301smx"
mybatis:
  mapper-locations: "classpath:mapper/**/*.xml"
  type-aliases-package: "com.qf.member.entity"
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: ture
  params: count=countSql
  reasonable: true

