

spring:
  datasource:
    druid:
      username: "root"
      password: "as200108"
      url: "jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false"
      max-active: 10



#CREATE TABLE `advertising` (
#`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '广告ID',
#`title` varchar(255) NOT NULL COMMENT '广告标题',
#`video_id` bigint(20) NOT NULL COMMENT '关联的视频ID',
#`push_type` tinyint(4) NOT NULL COMMENT '推送方式，1:全屏弹窗，2:插屏广告，3:原生广告',
#`push_time` datetime NOT NULL COMMENT '推送时间',
#`expiry_time` datetime NOT NULL COMMENT '失效时间',
#`create_time` datetime NOT NULL COMMENT '创建时间',
#`status` tinyint(4) NOT NULL COMMENT '广告状态，0:禁用，1:启用',
#PRIMARY KEY (`id`)
#) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='广告表';