

spring:
  servlet:
    multipart:
      max-request-size: 150MB
      max-file-size: 100MB
  datasource:
    druid:
      username: "root"
      password: "as200108"
      url: "jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false"
      max-active: 10

  profiles:
    active: "oss"


#spring:
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB





