

spring:
  datasource:
    druid:
      username: "root"
      password: "as200108"
      url: "jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false"
      max-active: 10






